import Head from "next/head";
import Header from "../../components/Header";
import Info from "../../components/Info";
import Faq from "../../components/Faq";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <Info />
      <Faq />
    </>
  );
};

export default Contact;
