import Header from "../../components/Header";
import CategoryCard from "../../components/CategoryCard";
import Head from "next/head";

const Shop = () => {
  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <style jsx>{`.grid-container{
    grid-template-columns: repeat(auto-fit, minmax(250px, 400px));`}</style>
      <div className="grid grid-container justify-center w-full mt-10 mb-10">
        <CategoryCard img="/shoes.png" link="/shop/shoes" btnText="Shoes" />
        <CategoryCard img="/shorts.png" link="/shop/shorts" btnText="Shorts" />
        <CategoryCard img="/shirts.png" link="/shop/shirts" btnText="Shirts" />
      </div>
    </>
  );
};

export default Shop;
