import React from "react";
import Header from "../../../components/Header";
import ItemCard from "../../../components/ItemCard";
import Head from "next/head";

export default function Shirts() {
  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <style jsx>{`.items-container{
    grid-template-columns: repeat(auto-fit, minmax(350px, 350px));`}</style>
      <div className="grid gap-10 items-container p-10 w-full justify-center">
        <ItemCard price={24.99} title="Sun Wars" link="/shirts.png" />
        <ItemCard title="Sun Dial" price={19.99} link="/sunDial.png" />
        <ItemCard title="The 2 Way" price={19.99} link="/2way.png" />
        <ItemCard title="Baige" price={17.99} link="/plainBaige.png" />
        <ItemCard title="Black" price={17.99} link="/plainBlack.png" />
        <ItemCard title="White Collar" price={29.99} link="/collar.png" />
        <ItemCard title="Black Collar" price={29.99} link="/blackCollar.png" />
      </div>
    </>
  );
}